### ISSUE TITLE
Yun's first autotest try

### ISSUE THREAD

**Issue by yshen16** [bu-rcs/PkgAutoTest#17]
I ran the PkgAutoTest nextflow pipeline for the first time and got the results as below: 

on screen output: 

N E X T F L O W  ~  version 21.10.6
Launching `pkgtest.nf` [awesome_miescher] - revision: d744e8d427
executor >  sge (186)
[a2/9d8879] process > runTests (xcrysden/1.6.2)   [100%] 186 of 186, failed: 2 \u2714
./report_test20240425.csv
Completed at: 26-Apr-2024 03:30:11
Duration    : 12h 18m 8s
CPU hours   : 350.5 (0% failed)
Succeeded   : 184
Ignored     : 2
Failed      : 2

However, when I opened the 'report_test20240425.csv' file and grep 'FAILED' test, I got 68 lines of failed records. My test folder is at 

/projectnb/rcstest/yshen16/PkgAutoTest/yuntest

I'll later find some time to dig down to it and see if I can get more clear picture of what's happened.

**Comment by milechin** [comment]
Yun, 

You had a pretty successful run. 186 modules tests were submitted.  2 tests failed on the Nextflow level.  Looking at the .nextflow.log file and searching for keyword "Error" :

``` console
cd /projectnb/rcstest/yshen16/PkgAutoTest/yuntest
less .nextflow.log
# Search for "Error"
```

There are two modules that have an "Error" state.  Here is a excerpt from the log:

```
Apr-25 15:19:44.692 [Task monitor] INFO  nextflow.processor.TaskProcessor - [b4/c3290a] NOTE: Process `runTests (grass/7.8.3)` terminated with an error exit status (1) -- Error is ignored
....

Apr-25 15:31:04.620 [Task monitor] INFO  nextflow.processor.TaskProcessor - [39/ad0b25] NOTE: Process `runTests (seadas/8.4.1)` terminated with an error exit status (1) -- Error is ignored

```

Looking at the working directory of these module tests reveals there are some permission issues encountered.  For grass/7.8.3:

``` console
cd /projectnb/rcstest/yshen16/PkgAutoTest/yuntest
less work/39/ad0b25c6b98b196dd5261a929fee35/.command.err

cp: cannot open '/share/pkg.8/grass/7.8.3/test/data/spearfish_grass70data_0/PERMANENT/.bash_history' for reading: Permission denied

```

For seadas/8.4.1:
``` console
cd /projectnb/rcstest/yshen16/PkgAutoTest/yuntest
less work/b4/c3290a5e1d60468eeb1015696dd802/.command.err

cp: cannot stat '/share/pkg.8/seadas/8.4.1/test/SeaDASTrainingPackageV1.2/6.Field_Measurements/CV5/FullCruise': Permission denied
cp: cannot stat '/share/pkg.8/seadas/8.4.1/test/SeaDASTrainingPackageV1.2/6.Field_Measurements/CV5/.DS_Store': Permission denied
cp: cannot stat '/share/pkg.8/seadas/8.4.1/test/SeaDASTrainingPackageV1.2/6.Field_Measurements/CV5/README.txt': Permission denied
cp: cannot stat '/share/pkg.8/seadas/8.4.1/test/SeaDASTrainingPackageV1.2/6.Field_Measurements/CV5/._.DS_Store': Permission denied
cp: cannot stat '/share/pkg.8/seadas/8.4.1/test/SeaDASTrainingPackageV1.2/6.Field_Measurements/CV5/Day317': Permission denied
cp: cannot stat '/share/pkg.8/seadas/8.4.1/test/SeaDASTrainingPackageV1.2/6.Field_Measurements/CV5/._README.txt': Permission denied

```

Both of these modules are mine, so I suspect I need to update permissions for these files.

Regarding the report, in the file report_test20240425.csv, there are 184 total records, which makes sense, since Nextflow determined there were 184 successful runs.  So other than the two modules that failed, this was a successful run.

I do see the overall test took 12 hours, which I think still suggests the modules with a GUI interface tests are not terminating properly and only end when the job runs out of time.  This is what we discussed yesterday and I am investigating this issue.

Thanks Yun!

**Comment by bu-bgregor** [comment]
Note - intel tests are failing due to the use of "pushd" - they're printing directory stacks to results.txt.  Easy to fix by not using pushd.

**Comment by bu-bgregor** [comment]
Discussed in the meeting.
